<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="56993" started-at="2021-05-27T10:01:14 IST" finished-at="2021-05-27T10:02:11 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="56993" started-at="2021-05-27T10:01:14 IST" finished-at="2021-05-27T10:02:11 IST">
      <class name="pom.POM_001">
        <test-method status="PASS" signature="startProcess()[pri:0, instance:pom.POM_001@17579e0f]" name="startProcess" is-config="true" duration-ms="22052" started-at="2021-05-27T10:01:14 IST" finished-at="2021-05-27T10:01:36 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startProcess -->
        <test-method status="FAIL" signature="login()[pri:0, instance:pom.POM_001@17579e0f]" name="login" duration-ms="34877" started-at="2021-05-27T10:01:36 IST" finished-at="2021-05-27T10:02:11 IST">
          <exception class="java.lang.NumberFormatException">
            <message>
              <![CDATA[For input string: "$16.51"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NumberFormatException: For input string: "$16.51"
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.lang.Integer.parseInt(Integer.java:569)
at java.lang.Integer.parseInt(Integer.java:615)
at pom.Login.vadilidity(Login.java:109)
at pom.POM_001.login(POM_001.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NumberFormatException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="endProcess()[pri:0, instance:pom.POM_001@17579e0f]" name="endProcess" is-config="true" duration-ms="1" started-at="2021-05-27T10:02:11 IST" finished-at="2021-05-27T10:02:11 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endProcess -->
      </class> <!-- pom.POM_001 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
